### ISSUE TITLE
Suggestions/Feedback

### ISSUE THREAD

**Issue by shazow** [limedaring/HelloWebApp-deploy-toolbelt#1]
- [x] Pretty sure PyPI won't render markdown, so your description field might need to be ReST. (This might have changed, worth testing)
- [x] I like shoving my README into the description field, rather than having a duplicated description file.
- [x] Maybe rename to `hellowebapp-toolbelt` or `hellowebapp-deploy`? Shorter and clearer, I think. (Note how `django-toolbelt` is not named `heroku-django-deploy-toolbelt`. :P)
  
    Another option: Move it under `github.com/HelloWebApp/django-toolbelt` and release it under `hwa-django-toolbelt`. If Kenneth's version was on Github, yours would be a proper fork of it.
  
    (Fwiw I like `hellowebapp-deploy` best.)
- [x] In the README, could mention its relation to django-toolbelt (for people who might find it familiar).
- [x] Do you need the hellowebapp-deploy-toolbelt subdirectory?

Once you pick a name you're happy with, you should totes push it to pypi just to see what it looks like etc. You can always push a newer version later.

**Comment by tracymakes** [comment]
Any thoughts on how to phrase the mention to django-toolbelt?

**Comment by shazow** [comment]
"This package is similar to django-toolbelt but does not require psycopg2 as a dependency. We may add more Hello Web App specific helpers here in the future."

**Comment by tracymakes** [comment]
Fo shizzle.
